# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.narodmon: debug

# https://www.home-assistant.io/integrations/debugpy/
# If you need to debug uncomment the line below
#debugpy:

narodmon:
  devices:
    - name: "Narodmon"
#      sensors:
#        - temperature
#        - humidity
      scan_interval:
        seconds: 61
